all:test3.cpp
	g++ test3.cpp -o test3.so -shared -fPIC  -I/home/software/local/include/python2.7 -I/home/huangzesang/share/my_env/boost/include -L/home/huangzesang/share/my_env/boost/lib -lboost_python
a:a.cpp
	g++ a.cpp -o a.so -shared -fPIC  -I/home/software/local/include/python2.7 -I/home/huangzesang/share/my_env/boost/include -L/home/huangzesang/share/my_env/boost/lib -lboost_python
