GFLAGS=-Wall -DUNIX -O2 --std=c++11 -fPIC


1: get_param_from_proto.cpp
	g++ -o get_param_from_proto get_param_from_proto.cpp /home/huangzesang/share/caffe-master/build/src/caffe/proto/caffe.pb.cc -I/home/software/local/include/ -I/home/huangzesang/share/caffe-master/build/src/caffe/proto/  -L/home/software/local/lib -lprotobuf
clean:
	rm -rf get_param_from_proto
