hello_bye:test2.cpp
	g++ test2.cpp -o hello_bye.so -shared -fPIC  -I/home/software/local/include/python2.7 -I/home/huangzesang/share/my_env/boost/include -L/home/huangzesang/share/my_env/boost/lib -lboost_python
