GFLAGS=-Wall -DUNIX -O2 --std=c++11 -fPIC


1: gflag_test.cpp
	#g++ -o gflag_test gflag_test.cpp -I/home/software/local/include -L/home/software/local/lib  -lgflags -lpthread
	g++ -o gflag_test gflag_test.cpp  -I /usr/include -lgflags -lpthread
clean:
	rm -rf gflag_test
